{Esta unidad contiene la definición de tipos de variables que se
necesitan en el proyecto general}
unit uTTipos;

interface

type

  TDimension = record
    m, n: Integer;
  end;

  TColorRGB = record
    r, g, b: Byte;
  end;

  TTipoMensaje = (tmMensaje, tmInformacion, tmAyuda, tmAdvertencia, tmError,
    tmCalculo, tmVacio);

  TNombreAutor = record
    Nombre1, Nombre2, Apellido1, Apellido2: String;
  end;

  TDupla = record
    a, b: Integer;
  end;

  TFecha = record
    Y, m, D: Integer;
  end;

  TTipoReferenciAPA = (trAPALibro, trAPAArticulo, trAPATesis, trAPAInternet);

  TRegistroReferencia = record
    Anyo: String;
    Titulo: String;
    Editorial: String;
    Ciudad: String;
    Volumen: String;
    Paginas: String;
    Revista: String;
    TipoReferencia: String;
    Universidad: String;
    URL: String;
    CantidadAutores: Integer;
    Recuperado: String;
  end;

  TTipoRecurso = record
    Nombre: String;
    Tipo: String;
    Cantidad: Integer;
    Descripcion: String;
    Propietario: String;
    ID: Integer;
  end;

  TObjetoSeleccionado = record
    ID: string;
    Nombre: string;
    Seleccionado: boolean;
  end;

const
  S_APP_ECUACION_CUADRATICA = 'ECUACION_CUADRATICA';
  S_APP_SISTEMA_ECUACIONES = 'SISTEMA_ECUACIONES';

  S_MATRIZ = 'MATRIZ';
  S_ACTIVIDAD = 'ACTIVIDAD';
  S_FASES = 'FASES';
  S_REDES = 'REDES';
  S_RED = 'RED';
  S_FACULTADES = 'FACULTADES';
  S_FACULTAD = 'FACULTAD';
  S_GRUPOS = 'GRUPOS';
  S_UNIDADES_EXTENSION = 'UNIDADES_EXTENSION';
  S_UNIDAD_EXTENSION = 'UNIDAD_EXTENSION';
  S_GRUPO = 'GRUPO';
  S_TEXTO = 'TEXTO';
  S_DIMENSION = 'DIMENSION';
  S_INVESTIGADORES = 'INVESTIGADORES';
  S_ASESORES = 'ASESORES';
  S_VECTOR = 'VECTOR';
  S_POLARIZACION = 'Polarizacion';
  S_PALABRA = 'PALABRA';
  S_ESTUDIANTE = 'ESTUDIANTE';
  S_CALCULOS = 'Calculos';
  S_CRONOGRAMA = 'Cronograma';
  S_DATOS = 'DATOS';
  S_ARCHIVOS = 'ARCHIVOS';
  S_MENSAJES = '';
  S_CONSULTAS = '';
  S_ERROR = '';
  S_SERVICIOS = 'SERVICIOS';
  S_LINEA_INVESTIGACION = 'LINEA_INVESTIGACION';
  S_VISITAS = 'VISITAS';
  S_COMITES = 'COMITES';
  S_DATOS_MAS = 'DATOS_MAS';
  S_DATOS_EX = 'DATOS_EX';
  S_DATOS_MES = 'DATOS_MES';
  S_LOTERIA = 'LOTERIA';
  S_USUARIO = 'USUARIO';
  S_PROYECTOS = 'PROYECTOS';
  S_PRODUCCIONES = 'PRODUCCIONES';
  S_PRODUCCION = 'PRODUCCION';
  S_PROYECTO = 'PROYECTO';
  S_PROGRAMAS = 'PROGRAMAS';
  S_PROGRAMA = 'PROGRAMA';
  S_PROFESIONALES = 'PROFESIONALES';
  S_PROFESIONAL = 'PROFESIONAL';
  s_PROPIETARIOS = 'PROPIETARIOS';
  S_ANTECEDENTES = 'ANTECEDENTES';
  S_OBJETIVOS = 'OBJETIVOS';
  S_PROBLEMA = 'PROBLEMA';
  S_PDF = 'PDF';
  S_RESUMEN = 'RESUMEN';
  S_RESULTADOS = 'RESULTADOS';
  S_CONCLUSIONES = 'CONCLUSIONES';
  S_JUSTIFICACION = 'JUSTIFICACION';
  S_JUEGO = 'JUEGO';
  S_NIVEL = 'NIVEL';
  S_INTRODUCCION = 'INTRODUCCION';
  S_METODOLOGIA = 'METODOLOGIA';
  S_MARCO_TEORICO = 'MARCO_TEORICO';
  S_REFERENCIAS = 'REFERENCIAS';
  S_RECURSO = 'RECURSO';
  S_CATEGORIAS = 'CATEGORIAS';
  S_REFERENCIA_ID = 'REFERENCIA';
  S_COLORES = 'COLORES';
  S_EVENTO = 'EVENTO';
  S_TAREA_ID = 'TAREA';

  V_CANTIDAD = 'CANTIDAD';
  V_CREDITOS = 'CREDITOS';
  V_CREDITO = 'CREDITO';
  V_PORCENTAJE = 'PORCENTAJE';
  V_ENTRADAS = 'ENTRADAS';
  V_MENSAJE = 'MENSAJE';
  V_SALIDAS = 'SALIDAS';
  V_SIGLA = 'SIGLA';
  V_CONCEPTO = 'CONCEPTO';
  V_DIRECTORIO = 'DIRECTORIO';
  V_DIRECTOR = 'DIRECTOR';
  V_ID_DIRECTOR = 'ID_DIRECTOR';
  V_REFERENCIA = 'REFERENCIA';
  V_REGISTRO_SOFTWARE = 'REGISTRO_SOFTWARE';
  V_PUNTAJE = 'PUNTAJE';
  V_ARCHIVO = 'ARCHIVO';
  V_TEXTO = 'TEXTO';
  V_COLUMNAS = 'COLUMNAS';
  V_FILAS = 'FILAS';
  V_NOMBRE = 'NOMBRE';
  V_LINK = 'LINK';
  V_SERVICIO = 'SERVICIO';
  V_NOMBRE_DECANO = 'NOMBRE_DECANO';
  V_NOMBRE_DIRECTOR = 'NOMBRE_DIRECTOR';
  V_ACREDITADO = 'ACREDITADO';
  V_MODALIDAD = 'MODALIDAD';
  V_CORREO = 'CORREO';
  V_DOCUMENTO = 'DOCUMENTO';
  V_CELULAR = 'CELULAR';
  V_CODIGO = 'CODIGO';
  V_ANO_INI = 'ANO_INI';
  V_ANO_FIN = 'ANO_FIN';
  V_MES_INI = 'MES_INI';
  V_MES_FIN = 'MES_FIN';
  V_DIA_FIN = 'DIA_FIN';
  V_DIA_INI = 'DIA_INI';
  V_CONTRA = 'CONTRA';
  V_TALLER = 'TALLER';
  V_CONFIRMADO = 'CONFIRMADO';
  V_SERIAL = 'SERIAL';
  V_SEDE = 'SEDE';
  V_NOMBRE_ID = 'NOMBRE';
  V_LINEA_INVESTIGACION = 'LINEA_INVESTIGACION';
  V_NOMBRE1 = 'NOMBRE1';
  V_NOMBRE2 = 'NOMBRE2';
  V_APELLIDO1 = 'APELLIDO1';
  V_APELLIDO2 = 'APELLIDO2';
  V_APELLIDOS = 'APELLIDOS';
  V_TELEFONO = 'TELEFONO';
  V_FASE = 'FASE';
  V_ANYO = 'ANYO';
  V_MES = 'MES';
  V_DIA = 'DIA';
  V_PALABRA = 'Palabra';
  V_PRONUNCIACION = 'Pronunciacion';
  V_TRADUCCION = 'Traduccion';
  V_RECUPERACION = 'FECHA_RECUPERACION';
  V_IDENTIFICACION = 'IDENTIFICACION';
  V_CEDULA = 'CEDULA';
  V_CVLAC = 'CVLAC';
  V_NACIONALIDAD = 'NACIONALIDAD';
  V_TITULO = 'TITULO';
  V_ISBN = 'ISBN';
  V_PROFESOR = 'PROFESOR';
  V_TITULO_PONENCIA = 'TITULO_PONENCIA';
  V_TITULO_POSTER = 'TITULO_POSTER';
  V_TITULO_COMUNICACION = 'TITULO_COMUNICACION';
  V_TITULO_TALLER = 'TITULO_TALLER';
  V_TITULO_OPTAR = 'TITULO_OPTAR';
  V_DESCRIPCION = 'DESCRIPCION';
  V_INVESTIGADORES = 'INVESTIGADORES';
  V_INVESTIGADOR = 'INVESTIGADOR';
  V_ENTIDAD_FINANCIADORA = 'ENTIDAD_FINANCIADORA';
  V_ASESOR = 'ASESOR';
  V_OBJETIVOS = 'OBJETIVOS';
  V_MARCO_TEORICO = 'MARCO_TEORICO';
  V_METODOLOGIA = 'METODOLOGIA';
  V_CONCLUSIONES = 'CONCLUSIONES';
  V_FECHA = 'FECHA';
  V_DURACION = 'DURACION';
  V_FECHA_INICIO = 'FECHA_INICIO';
  V_FECHA_FIN = 'FECHA_FIN';
  V_INSTITUCION = 'INSTITUCION';
  V_FACULTAD = 'FACULTAD';
  V_PROGRAMA = 'PROGRAMA';
  V_GRUPLAC = 'GRUPLAC';
  V_GRUPO = 'GRUPO';
  V_PERFIL = 'PERFIL';
  V_REVISTA = 'REVISTA';
  V_RED = 'RED';
  V_VOLUMEN = 'VOLUMEN';
  V_VINCULACION = 'VINCULACION';
  V_NUMERO = 'NUMERO';
  V_CIUDAD = 'CIUDAD';
  V_DEDICATORIA = 'DEDICATORIA';
  V_AGRADECIMIENTO = 'AGRADECIMIENTOS';
  V_PREFACIO = 'PREFACIO';
  V_EDITORIAL = 'EDITORIAL';
  V_EVENTO = 'EVENTO';
  V_FECHA_INCIO_EVENTO = 'FECHA_INICIO_EVENTO';
  V_FECHA_FIN_EVENTO = 'FECHA_FIN_EVENTO';
  V_TIPO_PARTICIPACION = 'TIPO_PARTICIPACION';
  V_NOMBRE_TRABAJO = 'NOMBRE_TRABAJO';
  V_URL = 'URL';
  V_PAGINAS = 'PAGINAS';
  V_UNIVERSIDAD = 'UNIVERSIDAD';
  V_CATEGORIA = 'CATEGORIA';
  V_RESPUETA = 'RESPUESTA';
  V_RESUMEN = 'RESUMEN';
  V_TIPO = 'TIPO';
  V_TIPO_TESIS = 'TIPO_TESIS';
  V_PREGUNTA = 'PREGUNTA';
  V_PESO = 'PESO';
  V_COLOR_TEMA = 'COLOR_TEMA';
  V_COLOR_FUENTE = 'COLOR_FUENTE';
  V_COLOR_ACTIVACION = 'COLOR_ACTIVACION';
  V_AUTOR_NOMBRE1 = 'NOMBRE1_AUTOR';
  V_AUTOR_NOMBRE2 = 'NOMBRE2_AUTOR';
  V_AUTOR_APELLIDO1 = 'APELLIDO1_AUTOR';
  V_AUTOR_APELLIDO2 = 'APELLIDO2_AUTOR';

  DS_DEFECTO = '';
  DI_DEFECTO = 0;
  DF_DEFECTO = 0;
  DB_DEFECTO = False;

  DS_VACIO = '';
  DI_VACIO = 0;
  DB_VACIO = False;

  TR_CORRECTO = 'Correcto';
  TR_INCORRECTO = 'Incorrecto';

  ITEM_PROGRAMADOR = 'Programador';
  ITEM_RUTA_DATOS = 'Ruta Datos';

  TIPO_REF_LIBRO = 'LIBRO';
  TIPO_REF_REVISTA = 'REVISTA';
  TIPO_REF_URL = 'URL';
  TIPO_REF_TESIS = 'TESIS';

  ACCION_CONECTAR_SERVIDOR = 'Accion:Conectar_Servidor';
  ACCION_PERMISO_CONCEDIDO = 'Accion:Permiso_Concedido';
  ACCION_TERMINAR_TRANSFERENCIA = 'Accion:Terminar_Transferencia';
  ACCION_INICIAR_TRANSFERENCIA = 'Accion:Iniciar_Transferencia';
  ACCION_CONFIRMAR_USUARIO = 'Accion:Confirmar_Usuario';
  ACCION_DESCONFIRMAR_USUARIO = 'Accion:Desconfirmar_Usuario';
  ACCION_ACTUALIZAR_CONFIRMADO = 'Accion:Actualizar_Confirmado';
  ACCION_DESACTUALIZAR_CONFIRMADO = 'Accion:Desactualizar_Confirmado';
  ACCION_REPARTIR_USUARIO = 'Accion:REPARTIR_USUARIO';
  ACCION_INCREMENTAR_USUARIOS = 'Accion:Incrementar_Usuarios';
  ACCION_ACTUALIZAR_REGISTRO = 'Accion:Actualizar_Registro';
  ACCION_CAMBIAR_REGISTRO = 'Accion:Cambiar_Registro';
  ACCION_VERIFICAR_CLIENTE = 'Accion:Verificar_Cliente';
  ACCION_ESTADO_CONECTADO = 'Accion:Estado';
  ACCION_TIPO_REGISTRO = 'Accion:Tipo_Registro';
  ACCION_ENVIAR_MENSAJE = 'Accin:Enviar_Mensaje';
  ACCION_RESPONDER_JUEGO = 'Accion:Responder_Juego';

  VAR_USUARIO = 'Usuario';
  VAR_NOMBRES = 'Nombres';
  VAR_APELLIDOS = 'Apellidos';
  VAR_DOCUMENTO = 'Documento';
  VAR_CORREO = 'Correo';
  VAR_TELEFONO = 'Telefono';
  VAR_CIUDAD = 'Ciudad';
  VAR_PERFIL = 'Perfil';
  VAR_TIPO = 'Tipo';
  VAR_INSTITUCION = 'Institucion';
  VAR_CONFIRMADO = 'Confirmado';

  DIR_GRAFICA_FUNCIONES = 'GRAFICA_FUNCIONES';

  FX_FUNCION_CONSTANTE = 'FUNCION_CONSTANTE';
  FX_FUNCION_CONSTANTE_ECUACION = 'FUNCION_CONSTANTE_ECUACION';

  LANG_HTML = 'Html';
  LANG_CSS = 'Css';
  LANG_JAVASCRIPT = 'Javascript';
  LANG_TYPESCRIPT = 'Typescript';
  LANG_PASCAL = 'Pascal';
  LANG_PYTHON = 'Python';
  LANG_SQL = 'SQL';
  LANG_JSON = 'JSON';

implementation

end.
